[package]
name = "cinebox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Native Windows-first desktop movie theater"

[dependencies]
cinebox-core.workspace = true
cinebox-indexer.workspace = true
cinebox-net.workspace = true
cinebox-parse.workspace = true
cinebox-tmdb.workspace = true
cinebox-torrserver.workspace = true
cinebox-player.workspace = true
egui.workspace = true
eframe.workspace = true
egui_extras.workspace = true
egui_glow.workspace = true
egui_material_icons.workspace = true
egui-async.workspace = true
tokio.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
open = "5"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

[build-dependencies]
anyhow.workspace = true
ico = "0.5.0"
resvg = "0.48.1"
winresource = "0.1"

[dev-dependencies]
egui_kittest.workspace = true

[lints]
workspace = true
