name: Feature request
description: An idea for Cinebox
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What you want to do
      description: The task or the inconvenience, not the solution yet.
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: How it could work
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Platforms
      options:
        - label: Windows
        - label: Linux
        - label: Android TV
