pub mod category;
pub mod home;
pub mod media;
mod paged;
pub mod person;
pub mod play;
pub mod player;
pub mod search;
mod trailers;
pub mod settings;
mod swr;
pub mod torrents;

pub use category::CategoryScreen;
pub use home::HomeScreen;
pub use media::MediaScreen;
pub use person::PersonScreen;
pub use player::PlayerScreen;
pub use search::SearchScreen;
pub use settings::SettingsScreen;
pub use torrents::TorrentsScreen;
